### ISSUE TITLE
Ash Dataset's court_normalized court variable may be wrong for DC

### ISSUE THREAD

**Issue by yukinko-iwasaki** [judgelord/courts#13]
Ash table has a normalized variable for court. 
For instance if the original court variable says 
"United States Court of Appeals for the First Circuit"
Then the normalized variable says  "first"
However, for the normalized variable == "Columbia",
the original court values seem to be wrong.
![image](https://user-images.githubusercontent.com/18432543/68547653-a15ffc00-03a9-11ea-8a59-88d396a070d5.png)

Colombia does not mean Federal circuit right? 

I did some fixes and the variable looks like this now
![image](https://user-images.githubusercontent.com/18432543/68547815-a8880980-03ab-11ea-8370-1cb3a09ba6bd.png)

Let me know if this looks right.

**Comment by ninavarsava** [comment]
I don't know if I'm understanding the issue, so let me know if you have follow up questions..

Here's an overview of the level of court we're interested in:

United States Court of Appeals: "any of 13 intermediate appellate courts within the United States federal judicial system, including **12 courts whose jurisdictions are geographically apportioned** and the United States Court of Appeals for the **Federal Circuit, whose jurisdiction is subject-oriented and nationwide**." (https://www.britannica.com/topic/United-States-Court-of-Appeals)

Our sample will include all 12 geographically apportioned courts: 1st through 11th, plus the D.C. (District of Columbia) Circuit. Our sample will **not** include the Court of Appeals for the Federal Circuit. This is a special subject-matter court.

The first and second snippets you posted seem to have nothing to do with each other. The first is a list of **Federal Circuit** cases and the second is a list of **D.C. Circuit** cases. In the second snippet, all five courts listed are the same court.

**Comment by yukinko-iwasaki** [comment]
Thanks for the clarification!!
I will go ahead with the corrected version of the dataset. 
And don't worry about the list of circuits listed in the snippet. These are from the raw court variables and we will be using (corrected)normalized version of the court variable.
And I will also name the DC circuit as 12th circuit! That will make the data processing code much easier to read! Thanks for the suggestion!
